[package]
name = "tablec"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
calamine = "0.25.0"
clap = "4.5.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.122"
structopt = "0.3.26"
