// 编译 cdylib fixture 并返回 .so 路径；为 cdylib_e2e.rs 提供 build_and_inspect helpers。
//
// - `build()`       → spawn `cargo build --release` 在 fixture crate 上，返回 .so 路径
// - `fixture_xlsx()` → 返回已提交的 fixture xlsx（5 行标准布局）
//
// 这个文件被 `tablec-core/src/test_support.rs` 通过 `include!` 引入；它本身不独立编译。
use std::path::{Path, PathBuf};
use std::process::Command;

/// Cargo manifest dir of the consuming crate (`tablec-core`).
fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Path to the fixture crate root.
fn fixture_crate_dir() -> PathBuf {
    manifest_dir().join("tests/fixtures/cdylib_parser")
}

/// Build the cdylib fixture crate and return the path to the resulting shared library.
///
/// Builds into a per-process temp dir so parallel `cargo test` invocations don't clobber each other.
pub fn build() -> PathBuf {
    let target_dir = std::env::temp_dir().join(format!(
        "tablec_cdylib_fixture_target_{}_{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0)
    ));
    let _ = std::fs::remove_dir_all(&target_dir);
    std::fs::create_dir_all(&target_dir).expect("create fixture target dir");

    let status = Command::new("cargo")
        .args(["build", "--release", "--target-dir"])
        .arg(&target_dir)
        .current_dir(fixture_crate_dir())
        .status()
        .expect("failed to spawn cargo build for cdylib fixture");
    assert!(status.success(), "cdylib fixture build failed");

    let so_name = if cfg!(target_os = "macos") {
        "libcdylib_parser_fixture.dylib"
    } else if cfg!(target_os = "windows") {
        "cdylib_parser_fixture.dll"
    } else {
        "libcdylib_parser_fixture.so"
    };
    let so = target_dir.join("release").join(so_name);
    assert!(
        so.exists(),
        "expected cdylib at {:?} (target_dir={:?})",
        so,
        target_dir
    );
    so
}

/// Path to the fixture xlsx shipped with the test crate.
///
/// Generated by `build_fixture_xlsx.rs` and committed at
/// `tests/fixtures/cdylib_parser/fixtures/test.xlsx`. Uses the standard
/// 5-row tablec layout that `FixtureParser` (delegating to
/// `StandardSchemaParser`) can parse.
pub fn fixture_xlsx() -> PathBuf {
    manifest_dir().join("tests/fixtures/cdylib_parser/fixtures/test.xlsx")
}

#[allow(dead_code)]
fn assert_exists(p: &Path) {
    assert!(p.exists(), "missing required fixture: {:?}", p);
}