[package]
name = "tablec-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
tablec-core = { path = "../tablec-core" }
clap = { version = "4.5.13", features = ["derive"] }
tempfile = "3.10.1"
rust_xlsxwriter = "0.90.1"
calamine = "0.25.0"
rand = "0.9.2"
glob = "0.3"

[[bin]]
name = "tablec"
path = "src/main.rs"

